"""refactor_updates

Revision ID: 70d23fdd417c
Revises: 
Create Date: 2026-05-12 06:31:44.812859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '70d23fdd417c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashmovement', schema=None) as batch_op:
        batch_op.drop_column('sale_id')
        batch_op.drop_column('payment_id')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('method')
        batch_op.drop_column('status')
        batch_op.drop_column('reference')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_cash', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('amount_transfer', sa.Float(), nullable=False))

    with op.batch_alter_table('saleitem', schema=None) as batch_op:
        batch_op.alter_column('cost_price_at_sale',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('discount_amount')

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('feature_afip')
        batch_op.drop_column('feature_accounts')
        batch_op.drop_column('feature_vendors')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_vendors', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True))
        batch_op.add_column(sa.Column('feature_accounts', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True))
        batch_op.add_column(sa.Column('feature_afip', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True))

    with op.batch_alter_table('saleitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_amount', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
        batch_op.alter_column('cost_price_at_sale',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('amount_transfer')
        batch_op.drop_column('amount_cash')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'confirmed'"), nullable=True))
        batch_op.add_column(sa.Column('method', sa.VARCHAR(length=20), server_default=sa.text("'cash'"), nullable=True))

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('cashmovement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sale_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'payment', ['payment_id'], ['id'])
        batch_op.create_foreign_key(None, 'sale', ['sale_id'], ['id'])

    # ### end Alembic commands ###
