"""Add onboarding and TenantCatalog

Revision ID: 8ac4d5bd1552
Revises: e00613d1d525
Create Date: 2026-06-23 11:40:59.157397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ac4d5bd1552'
down_revision: Union[str, Sequence[str], None] = 'e00613d1d525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenantcatalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenantcatalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenantcatalog_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenantcatalog_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_onboarded', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('onboarding_step', sa.Integer(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('onboarding_step')
        batch_op.drop_column('is_onboarded')

    with op.batch_alter_table('tenantcatalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenantcatalog_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenantcatalog_product_id'))

    op.drop_table('tenantcatalog')
    # ### end Alembic commands ###
