"""add refresh token table

Revision ID: baaab6e3a4c2
Revises: vibecloud_all_fixes
Create Date: 2026-06-20 23:18:58.080131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'baaab6e3a4c2'
down_revision: Union[str, Sequence[str], None] = 'vibecloud_all_fixes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refreshtoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refreshtoken_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refreshtoken_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refreshtoken_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('accountreceivable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accountreceivable_client'))
        batch_op.drop_constraint(batch_op.f('uq_accountreceivable_sale_id'), type_='unique')
        batch_op.create_index(batch_op.f('ix_accountreceivable_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accountreceivable_sale_id'), ['sale_id'], unique=True)

    with op.batch_alter_table('cashmovement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix__alembic_tmp_cashmovement_purchase_id'))
        batch_op.drop_index(batch_op.f('ix__alembic_tmp_cashmovement_sale_id'))

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_receivable_id'), ['receivable_id'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_product_barcode'))
        batch_op.create_index(batch_op.f('ix_product_barcode'), ['barcode'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_barcode'))
        batch_op.create_index(batch_op.f('ix_product_barcode'), ['barcode'], unique=1)
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_receivable_id'))

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('cashmovement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__alembic_tmp_cashmovement_sale_id'), ['sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix__alembic_tmp_cashmovement_purchase_id'), ['purchase_id'], unique=False)

    with op.batch_alter_table('accountreceivable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accountreceivable_sale_id'))
        batch_op.drop_index(batch_op.f('ix_accountreceivable_client_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_accountreceivable_sale_id'), ['sale_id'])
        batch_op.create_index(batch_op.f('ix_accountreceivable_client'), ['client_id'], unique=False)

    with op.batch_alter_table('refreshtoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refreshtoken_user_id'))
        batch_op.drop_index(batch_op.f('ix_refreshtoken_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refreshtoken_tenant_id'))

    op.drop_table('refreshtoken')
    # ### end Alembic commands ###
