"""add uiconfig table

Revision ID: e00613d1d525
Revises: baaab6e3a4c2
Create Date: 2026-06-21 08:39:06.493615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e00613d1d525'
down_revision: Union[str, Sequence[str], None] = 'baaab6e3a4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uiconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('page_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('layout_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('theme_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'page_name', name='uq_uiconfig_tenant_page')
    )
    with op.batch_alter_table('uiconfig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uiconfig_page_name'), ['page_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_uiconfig_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uiconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uiconfig_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_uiconfig_page_name'))

    op.drop_table('uiconfig')
    # ### end Alembic commands ###
